baseURL = "http://akshayshipurkar.com/"
languageCode = "en-us"
title = "Akshay Shipurkar"
author = "Akshay Shipurkar"
copyright = "Akshay Shipurkar All rights reserved."
#theme = "ananke"
theme = "hugo-zen"

[params]
	logo = "https://scontent.fbom2-1.fna.fbcdn.net/v/t1.0-9/20245911_1623348447689435_2922540952725085538_n.jpg?oh=adfe693894f00b4acbd963be8f5fb598&oe=5A7D203C"
	twitter = "https://twitter.com/akkishipurkar"
	facebook = "https://www.facebook.com/akshayshipurkar"
	github = "https://github.com/Akki356"
	email = "akshay<nospam>shipurkar<at>gmail<dot>com"

