## Basic Configuration

baseurl = "https://www.akshayshipurkar.com" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Akshay Shipurkar"
title = "Akshay Shipurkar"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Akshay Shipurkar"
intro = "DevOps Engineer | Open Source Evangelist | Multipotentialite "
description = "Now @Jio Cloud DevOps.  <br/> \"What is F times 5? It's Fleventy-five.\""
authorimage = "AkshayShipurkar.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Akshay Shipurkar akshays personal website blog"
keywords = "akshay,shipurkar,blog,developer,DevOps,Open-Source,openstack"

## Social Accounts
[params.social]
github = "Akki356"
instagram = "akshayshipurkar"
linkedin = "akshayshipurkar"
twitter = "akkishipurkar"
facebook = "akshayshipurkar"
google = "akshayshipurkar@gmail.com"
#stackoverflow = "<username>"
email = "AkshayShipurkar<nospam><at>gmail<dot>com"

## Extras
[params.extra]
copyright = "© 2016. Akshay Shipurkar. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true 
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
#[[menu.main]]
#    name = "coderag"
#    identifier = "coderag"
#    weight = 300
#    url = "/coderag/"
